[run]
init_cmds = [
  ["GO_BUILD_DEV=1", "make", "build-go"],
  ["make", "gen-jsonnet"],
  ["GO_BUILD_DEV=1", "make", "build-cli"],
  ["GO_BUILD_DEV=1", "make", "build-server"],
  ["./bin/grafana-server", "-packaging=dev","--config", "./conf/development.ini"]
]
watch_all = true
follow_symlinks = true
watch_dirs = [
  "$WORKDIR/apps",
  "$WORKDIR/pkg",
  "$WORKDIR/public/views",
  "$WORKDIR/conf",
  "$WORKDIR/devenv/dev-dashboards",
]
watch_exts = [".go", ".ini", ".toml", ".template.html"]
ignore_files = [".*_gen.go"]
build_delay = 1500
cmds = [
  ["GO_BUILD_DEV=1", "make", "build-go-fast"],
  ["make", "gen-jsonnet"],
  ["GO_BUILD_DEV=1", "make", "build-server"],
  ["./bin/grafana-server", "-packaging=dev", "--config", "./conf/development.ini"]
]
